# Generated by Django 5.0.1 on 2024-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                ],
                max_length=30,
            ),
        ),
    ]
