# Generated by Django 5.0.1 on 2024-01-26 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("coupler", "Coupler"),
                            ("clampcylinder", "Clamp Cylinder"),
                            ("nylontubing", "Nylon Tubing"),
                            ("silencer", "Silencer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("orderpicker", "Order Picker"),
                    ("stockpurchaser", "Stock Purchaser"),
                ],
                max_length=30,
            ),
        ),
    ]
