# Generated by Django 5.0.1 on 2024-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("map", models.ImageField(upload_to="map")),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("nylontubing", "Nylon Tubing"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
