# Generated by Django 5.0.1 on 2024-02-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_map_depart_alter_product_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("clampcylinder", "Clamp Cylinder"),
                    ("silencer", "Silencer"),
                    ("nylontubing", "Nylon Tubing"),
                    ("coupler", "Coupler"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("stockpurchaser", "Stock Purchaser"),
                    ("admin", "Admin"),
                    ("orderpicker", "Order Picker"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_list",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
