# Generated by Django 5.0.1 on 2024-02-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlist",
            name="list_id",
        ),
        migrations.AddField(
            model_name="productlist",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("orderpicker", "Order Picker"),
                    ("stockpurchaser", "Stock Purchaser"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
