# Generated by Django 5.0.1 on 2024-02-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_productlist_list_id_productlist_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("silencer", "Silencer"),
                    ("nylontubing", "Nylon Tubing"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("orderpicker", "Order Picker"),
                    ("admin", "Admin"),
                    ("stockpurchaser", "Stock Purchaser"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProductListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("coupler", "Coupler"),
                            ("silencer", "Silencer"),
                            ("nylontubing", "Nylon Tubing"),
                            ("clampcylinder", "Clamp Cylinder"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productlist",
                    ),
                ),
            ],
        ),
    ]
