# Generated by Django 5.0.1 on 2024-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("nylontubing", "Nylon Tubing"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("coupler", "Coupler"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("nylontubing", "Nylon Tubing"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("coupler", "Coupler"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                ],
                max_length=30,
            ),
        ),
    ]
