# Generated by Django 5.0.1 on 2024-02-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlist",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
