# Generated by Django 5.0.1 on 2024-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_map_destination_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="depart",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("coupler", "Coupler"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="destination",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("coupler", "Coupler"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("coupler", "Coupler"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("coupler", "Coupler"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
