# Generated by Django 5.0.1 on 2024-02-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_product_location_alter_map_depart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlistitem",
            name="location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="map",
            name="depart",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="destination",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("coupler", "Coupler"),
                    ("location1", "Location 1"),
                    ("location2", "Location 2"),
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("stockpurchaser", "Stock Purchaser"),
                    ("orderpicker", "Order Picker"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
