# Generated by Django 5.0.1 on 2024-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_map_depart_alter_map_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="depart",
            field=models.CharField(
                choices=[("location2", "Location 2"), ("location1", "Location 1")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="destination",
            field=models.CharField(
                choices=[("location2", "Location 2"), ("location1", "Location 1")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                    ("nylontubing", "Nylon Tubing"),
                ],
                max_length=30,
            ),
        ),
    ]
