# Generated by Django 5.0.1 on 2024-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_map_depart_alter_map_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default=1, upload_to="product"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productlistitem",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("nylontubing", "Nylon Tubing"),
                    ("silencer", "Silencer"),
                    ("coupler", "Coupler"),
                    ("clampcylinder", "Clamp Cylinder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("orderpicker", "Order Picker"),
                    ("stockpurchaser", "Stock Purchaser"),
                    ("admin", "Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
